$ErrorActionPreference = 'Stop'

$targetRoot = 'C:\Users\firio\Desktop\Website2026\HaiMy\dist'
$articles = @(
    @{ Slug='harga-iphone-18-pro-duo-malaysia'; Category='Gajet'; Time='4 min'; Image='hero-youth.png'; Source='https://fuzz.my/20260910043142942'; Title='Harga iPhone 18 Pro dan Duo Malaysia: dari RM5,499 hingga RM15,499'; Intro='Barisan iPhone baharu yang dilaporkan tiba ke Malaysia membawa jurang harga yang sangat besar. Sebelum pra-tempah, pembeli perlu melihat kapasiti storan, tarikh jualan dan keperluan sebenar.'; Body='<h2>Harga yang dilaporkan</h2><p>Menurut laporan Fuzz.my, iPhone 18 Pro bermula pada RM5,499 untuk 256GB, manakala iPhone 18 Pro Max bermula pada RM5,999. Model iPhone Duo pula dilaporkan bermula pada RM9,499 dan boleh mencecah RM15,499 untuk storan 2TB.</p><h2>Jangan lihat nombor permulaan sahaja</h2><p>Harga terendah biasanya bukan pilihan yang sama untuk setiap orang. Rakaman video, foto, permainan dan fail kerja boleh membuat storan cepat penuh. Bandingkan harga versi storan yang benar-benar sesuai, bukan sekadar harga pada poster.</p><h2>Tarikh dan ketersediaan</h2><p>Fuzz.my menyatakan pra-tempah iPhone 18 Pro bermula 12 September dengan jualan pertama pada 18 September, manakala iPhone Duo menyusul kemudian. Semak halaman rasmi penjual sebelum membuat bayaran kerana tarikh serta stok boleh berubah.</p>' },
    @{ Slug='iphone-18-pro-berbaloi-atau-tidak'; Category='Gajet'; Time='5 min'; Image='hero-youth.png'; Source='https://fuzz.my/20260911192442993'; Title='iPhone 18 Pro: upgrade sebenar atau sekadar nombor baharu?'; Intro='A20 Pro, kamera utama 48MP dengan apertur boleh ubah dan fokus AI menjadikan siri iPhone 18 Pro menarik. Soalan lebih penting ialah sama ada perubahan itu memberi kesan kepada cara anda menggunakan telefon.'; Body='<h2>Kuasa bukan satu-satunya alasan</h2><p>Fuzz.my melaporkan A20 Pro menggunakan binaan 2nm serta peningkatan prestasi dan grafik. Untuk pengguna yang masih menggunakan telefon dua atau tiga generasi lalu, lompatannya mungkin lebih terasa berbanding pengguna model terkini.</p><h2>Kamera yang lebih fleksibel</h2><p>Salah satu perubahan yang diberi tumpuan ialah apertur boleh ubah pada kamera utama. Ciri ini berpotensi memberi lebih kawalan dalam keadaan cahaya berbeza, tetapi hasil sebenar masih bergantung pada cara seseorang merakam.</p><h2>Siapa patut tunggu</h2><p>Jika telefon sekarang masih lancar, bateri sihat dan kamera mencukupi, tunggu ulasan bebas serta harga telco. Jika kerja anda bergantung pada video, foto atau aplikasi berat, naik taraf boleh lebih mudah untuk dibenarkan.</p>' },
    @{ Slug='dakwaan-kebocoran-data-misi-rakyat'; Category='Digital'; Time='4 min'; Image='thumb-digital-feed.png'; Source='https://fuzz.my/20260908171942905'; Title='Data Misi Rakyat didakwa dijual: langkah segera untuk pengguna'; Intro='Laporan mengenai data pelanggan yang didakwa ditawarkan untuk dijual perlu diambil serius, tetapi tidak perlu mencetuskan panik. Fokus kepada langkah perlindungan yang boleh dibuat sekarang.'; Body='<h2>Ini masih dakwaan</h2><p>Fuzz.my melaporkan satu pihak mendakwa mempunyai pangkalan data berkaitan Misi Rakyat, termasuk rekod pelanggan, rider dan vendor. Dakwaan tersebut tidak sama dengan pengesahan bebas, jadi pembaca perlu mengelakkan penyebaran butiran peribadi atau pautan yang meragukan.</p><h2>Tukar akses yang berkaitan</h2><p>Jika anda pernah menggunakan perkhidmatan itu, tukar kata laluan—terutama jika kata laluan sama digunakan pada e-mel atau aplikasi lain. Hidupkan pengesahan dua faktor pada e-mel dan bank jika tersedia.</p><h2>Berwaspada terhadap scam susulan</h2><p>Jangka panggilan, SMS atau e-mel yang menggunakan nama, alamat atau sejarah pesanan untuk kelihatan meyakinkan. Jangan kongsi OTP, nombor kad atau kata laluan. Gunakan aplikasi rasmi untuk menghubungi sokongan.</p>' },
    @{ Slug='iphone-18-pro-dan-pro-max-apa-baru'; Category='Gajet'; Time='4 min'; Image='hero-youth.png'; Source='https://fuzz.my/20260910040842940'; Title='iPhone 18 Pro dan Pro Max: semua perubahan utama'; Intro='Apple dikatakan memfokuskan model Pro sahaja untuk generasi baharu ini. Berikut perkara yang patut diperhatikan sebelum membandingkan harga atau merancang naik taraf.'; Body='<h2>Skrin dan prestasi</h2><p>Menurut Fuzz.my, iPhone 18 Pro menggunakan skrin 6.3 inci manakala Pro Max menggunakan skrin 6.9 inci. Kedua-duanya dilaporkan menggunakan cip A20 Pro yang sama, jadi pilihan utama biasanya saiz, bateri dan cara anda menggunakan kamera.</p><h2>Kamera sebagai fokus</h2><p>Laporan itu turut menyebut sistem tiga kamera 48MP serta apertur boleh ubah pada kamera utama. Bagi pembeli biasa, lebih penting untuk melihat contoh foto dan video dunia sebenar daripada sekadar angka megapiksel.</p><h2>Buat perbandingan yang jujur</h2><p>Bandingkan telefon lama dengan keperluan semasa: berapa banyak storan digunakan, sama ada bateri masih tahan, dan sama ada kamera atau prestasi benar-benar menghalang kerja harian.</p>' },
    @{ Slug='ios-27-tarikh-kemas-kini'; Category='Aplikasi'; Time='4 min'; Image='thumb-digital-feed.png'; Source='https://fuzz.my/20260910164242984'; Title='iOS 27 tiba: iPhone anda dapat kemas kini atau tidak?'; Intro='Kemas kini besar boleh membawa ciri baharu, tetapi masa terbaik untuk memasangnya tidak semestinya pada minit pertama ia tersedia.'; Body='<h2>Tarikh yang dilaporkan</h2><p>Fuzz.my menyatakan versi stabil iOS 27 akan tersedia pada 14 September 2026 dan memberi fokus kepada fungsi AI serta peningkatan pengalaman pengguna. Semak tetapan Software Update pada iPhone untuk status tepat bagi peranti anda.</p><h2>Sediakan telefon dahulu</h2><p>Buat sandaran, sediakan ruang storan dan pastikan bateri mencukupi atau sambungkan pengecas. Kemas kini aplikasi penting selepas sistem selesai dikemas kini supaya keserasian lebih baik.</p><h2>Perlu kemas kini segera?</h2><p>Jika iPhone digunakan untuk kerja atau urusan penting, menunggu beberapa hari membolehkan isu awal dikenal pasti. Jika kemas kini membawa tampalan keselamatan kritikal, jangan tunggu terlalu lama.</p>' },
    @{ Slug='a20-pro-2nm-apa-maksudnya'; Category='AI'; Time='4 min'; Image='creator-desk.png'; Source='https://fuzz.my/20260910041242945'; Title='A20 Pro 2nm: apa maksudnya untuk pengguna iPhone'; Intro='Istilah 2nm, GPU dan Neural Engine sering kedengaran seperti bahan pemasaran. Nilai sebenar cip baharu terletak pada apa yang dapat dilakukan oleh telefon setiap hari.'; Body='<h2>Prestasi dan kecekapan</h2><p>Fuzz.my melaporkan Apple mendakwa A20 Pro menawarkan peningkatan prestasi sehingga 20% dan grafik sehingga 40% berbanding generasi sebelumnya. Angka pembuat ialah petunjuk awal; ujian bebas masih penting untuk melihat kesan pada aplikasi sebenar.</p><h2>Kenapa AI disebut sekali</h2><p>Cip itu juga dikatakan mempunyai GPU dengan neural accelerator dan Neural Engine yang lebih berkuasa. Secara praktikal, ini boleh menyokong ciri AI pada peranti dengan lebih pantas tanpa setiap tugasan perlu dihantar ke pelayan.</p><h2>Jangan beli hanya kerana proses 2nm</h2><p>Untuk kebanyakan pengguna, bateri, kamera, sokongan perisian dan harga masih lebih penting. Cip baharu paling berbaloi apabila ia menyelesaikan masalah penggunaan anda, bukan kerana namanya lebih kecil.</p>' },
    @{ Slug='asus-rog-g1000-malaysia'; Category='Gaming'; Time='4 min'; Image='thumb-gaming.png'; Source='https://fuzz.my/20260914190243039'; Title='PC gaming RM32,999: apa sebenarnya yang anda dapat dengan ROG G1000'; Intro='ASUS membawa desktop ROG G1000 ke Malaysia pada harga yang meletakkannya dalam kategori premium. Spesifikasi tinggi memang menarik, tetapi pembeli perlu tahu apa yang dibayar.'; Body='<h2>Komponen kelas atas</h2><p>Menurut Fuzz.my, ROG G1000 dipadankan dengan Ryzen 9 9950X3D, ROG Astral GeForce RTX 5080 OC, RAM DDR5 64GB dan storan 1TB PCIe 4.0. Ia juga menggunakan sistem penyejukan 420mm serta bekalan kuasa 1000W.</p><h2>Harga termasuk ekosistem</h2><p>Harga RM32,999 bukan hanya untuk FPS tinggi. Ia juga merangkumi casing besar, penyejukan, sambungan moden dan aksesori ROG. Namun, pembeli yang selesa membina PC sendiri mungkin mendapat konfigurasi yang berbeza pada bajet sama.</p><h2>Siapa sasaran sebenar</h2><p>Ini lebih sesuai untuk pemain kompetitif, pencipta video atau pengguna profesional yang mahukan sistem siap guna. Untuk gaming 1080p atau 1440p biasa, pilihan yang jauh lebih murah masih mencukupi.</p>' },
    @{ Slug='xbox-cloud-gaming-had-masa'; Category='Gaming'; Time='3 min'; Image='thumb-gaming.png'; Source='https://fuzz.my/20260904112942821'; Title='Xbox Cloud Gaming mungkin ada had masa: apa maknanya untuk pemain'; Intro='Laporan tentang had jam bulanan boleh mengubah cara pelanggan melihat langganan cloud gaming. Buat masa ini, pembaca perlu menganggapnya sebagai perubahan yang dilaporkan sehingga Microsoft mengesahkan butiran tempatan.'; Body='<h2>Had yang dilaporkan</h2><p>Fuzz.my melaporkan Xbox Cloud Gaming mungkin memperkenalkan had masa mengikut pelan bermula November: 15 jam untuk Ultimate, 10 jam untuk Premium dan lima jam untuk Essential. Laporan itu juga menyebut jam yang tidak digunakan boleh dibawa ke bulan berikutnya.</p><h2>Siapa paling terkesan</h2><p>Pemain yang hanya mencuba beberapa sesi sebulan mungkin tidak melihat perubahan besar. Pengguna yang menjadikan cloud gaming sebagai cara utama bermain akan mahu mengira jam mereka sebelum memperbaharui langganan.</p><h2>Tunggu pengesahan</h2><p>Harga, pelan dan ketersediaan boleh berbeza mengikut negara. Semak pengumuman Xbox Malaysia atau Microsoft sebelum membuat keputusan langganan berdasarkan laporan ini.</p>' }
)

foreach ($article in $articles) {
    $html = @"
<!doctype html><html lang="ms"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="$($article.Intro)"><meta property="og:type" content="article"><meta property="og:title" content="$($article.Title) — HAI.my"><meta property="og:url" content="https://hai.my/$($article.Slug).html"><title>$($article.Title) — HAI.my</title><link rel="stylesheet" href="tech-article.css"></head><body><div class="top wrap">HAI.my · Teknologi dalam bahasa kita</div><header><div class="wrap nav"><a href="index.html"><img class="logo" src="logo-hai.png" alt="HAI.my"></a><nav><a href="index.html#terkini">Terkini</a><a href="index.html#tools">Pilihan Editor</a></nav><a class="back" href="index.html#terkini">← Semua artikel</a></div></header><main><article class="article"><div class="tag">$($article.Category)</div><h1>$($article.Title)</h1><div class="meta">HAI.MY · $($article.Time.ToUpper()) BACA · 15 SEPTEMBER 2026</div><figure class="article-figure"><img class="cover" src="$($article.Image)" alt="Ilustrasi artikel $($article.Category)"></figure><p class="intro">$($article.Intro)</p><div class="copy">$($article.Body)<div class="source-note"><strong>Sumber dan konteks:</strong> Artikel ini ialah penulisan asal HAI.my yang dibuat berdasarkan laporan <a href="$($article.Source)" target="_blank" rel="noopener noreferrer">Fuzz.my</a>. Harga, spesifikasi, tarikh dan dasar boleh berubah; semak pengumuman rasmi sebelum membuat pembelian atau keputusan penting.</div></div><section class="related"><div class="related-kicker">TERUSKAN MEMBACA</div><h2 id="related-title">Artikel teknologi terkini</h2><div class="related-grid"><a class="related-card" href="harga-iphone-18-pro-duo-malaysia.html"><img src="hero-youth.png" alt=""><span><small>GAJET</small><strong>Harga iPhone 18 Pro dan Duo Malaysia</strong><em>Baca artikel →</em></span></a><a class="related-card" href="dakwaan-kebocoran-data-misi-rakyat.html"><img src="thumb-digital-feed.png" alt=""><span><small>DIGITAL</small><strong>Langkah segera selepas dakwaan insiden data</strong><em>Baca artikel →</em></span></a></div></section></article></main></body></html>
"@
    Set-Content -LiteralPath (Join-Path $targetRoot ($article.Slug + '.html')) -Value $html -Encoding utf8
}

$indexPath = Join-Path $targetRoot 'index.html'
$index = Get-Content -Raw -LiteralPath $indexPath
$cards = foreach ($article in $articles) {
    '<a class="story" data-category="' + $article.Category + '" href="' + $article.Slug + '.html"><div class="story-image" style="min-height:0;height:190px;margin-bottom:18px"><img src="' + $article.Image + '" alt="Thumbnail artikel ' + $article.Category + '" loading="lazy"></div><div class="story-meta"><span>' + $article.Category + '</span><span>' + $article.Time + '</span></div><h3>' + $article.Title + '</h3></a>'
}
$index = $index.Replace('<div class="stories">', '<div class="stories">' + ($cards -join ''))
$index = $index.Replace('<button class="filter" data-filter="Digital">Digital</button>', '<button class="filter" data-filter="Digital">Digital</button><button class="filter" data-filter="Gaming">Gaming</button>')
Set-Content -LiteralPath $indexPath -Value $index -Encoding utf8
